import type { PluginInput, PluginOutputError } from "@varavel/vdl-plugin-sdk";
import * as options from "@varavel/vdl-plugin-sdk/utils/options";
import { isValidGoPackageName } from "../../shared/naming";
import type { GeneratorOptions, GeneratorTarget } from "../model/types";

const DEFAULT_PACKAGE_NAME = "vdlrpc";

/**
 * Resolves and validates the raw plugin options.
 */
export function resolveGeneratorOptions(input: PluginInput): {
  options?: GeneratorOptions;
  errors: PluginOutputError[];
} {
  const packageName = options
    .getOptionString(input.options, "package", DEFAULT_PACKAGE_NAME)
    .trim();
  const typesImport = options
    .getOptionString(input.options, "typesImport", "")
    .trim();
  const targetRaw = options.getOptionString(input.options, "target", "").trim();
  const target = isGeneratorTarget(targetRaw) ? targetRaw : undefined;

  const errors: PluginOutputError[] = [];

  if (!typesImport) {
    errors.push({
      message:
        'Missing required option "typesImport". Point it to the Go package generated by varavelio/vdl-plugin-go plugin.',
    });
  }

  if (!target) {
    errors.push({
      message:
        'Missing or invalid option "target". Use either "client" or "server".',
    });
  }

  if (!packageName) {
    errors.push({
      message: 'Option "package" cannot be empty when provided.',
    });
  } else if (!isValidGoPackageName(packageName)) {
    errors.push({
      message: `Invalid Go package name ${JSON.stringify(packageName)}. Use a lowercase Go identifier.`,
    });
  }

  if (errors.length > 0 || !target) {
    return { errors };
  }

  return {
    errors: [],
    options: {
      packageName,
      target,
      typesImport,
    },
  };
}

/**
 * Reports whether a raw option value is a supported generator target.
 */
function isGeneratorTarget(value: string): value is GeneratorTarget {
  return value === "client" || value === "server";
}
